language: csharp
solution: Natasha.sln
dist: xenial
dotnet: 3.1.100
mono: none

branches:
  only:
  - master

os:
  - linux
  - osx

osx_image: xcode9.4
before-script:

script:
 - export PATH="$PATH:$HOME/.dotnet/tools"
 - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
 - flubu Rebuild.Server -apiKey=${Nuget_Api_Key}
