version: 0.7.1.{build}
image:
- Ubuntu1804
- Visual Studio 2019




configuration: Release
clone_depth: 50

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
    - master
#skip_branch_with_pr: true
skip_commits:
  files:
    - docs/*
    - Image/*
    - media/*
    - LICENSE
    - mkdocs.yml
    - README.md
    - .travis.yml
    - .gitignore
    - azure-pipelines.yml

for:
-
  matrix:
    only:
      - image: Visual Studio 2019


  install:
  #- ps: cd c:\projects\xxx
                
  before_build:
  - ps: dotnet restore
  - ps: choco install opencover.portable
  - ps: choco install codecov

  build_script:
  - ps: dotnet build -c Release
  

  test_script:
  - ps: dotnet test
  - ps: OpenCover.Console.exe -register:user -target:"dotnet" -targetargs:".\NatashaUT\bin\Debug\netcoreapp2.2\NatashaUT.dll -noshadow" -output:".\coverage.xml" -oldstyle
  - ps: codecov -f "coverage.xml" -t %COVERAGE_KEY%

-
  matrix:
    only:
      - image: Ubuntu1804

  services:


  install:

    
  before_build:
  - sh: dotnet restore
  
  build_script:
  - sh: dotnet build -c Release
  
  test_script:
  - ps: dotnet test