version: 1.0.0.{build}
image:
- Ubuntu1804
- Visual Studio 2019




configuration: Release
clone_depth: 50

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
    - master
#skip_branch_with_pr: true
skip_commits:
  files:
    - docs/*
    - Image/*
    - media/*
    - LICENSE
    - mkdocs.yml
    - README.md
    - .travis.yml
    - .gitignore
    - azure-pipelines.yml
    - lang/*
    - article/*

for:
-
  matrix:
    only:
      - image: Visual Studio 2019


  install:
  #- ps: cd c:\projects\xxx
                
  before_build:
  - ps: dotnet restore
  - ps: choco install opencover.portable
  - ps: choco install codecov

  build_script:
  - ps: dotnet build -c Release
  

  test_script:
  - ps: OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:test -output:".\coverage.xml" -oldstyle
  - ps: codecov -f "coverage.xml" -t %COVERAGE_KEY%

-
  matrix:
    only:
      - image: Ubuntu1804

  services:


  install:

    
  before_build:
  - sh: dotnet tool install --global FlubuCore.GlobalTool --version 4.2.3
  
  build_script:
  - sh: flubu Rebuild
  
  test_script:
  - ps: dotnet test