# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - appveyor.yml
    - .travis.yml
    - lang/*
    - article/*
    - docs/*
    - .github/*

jobs:
    

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  
  steps:


  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '5.0.x'
  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '6.0.x'

  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '3.1.x'

  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test
      projects: './test/NatashaFunctionUT'
      arguments: '-c Release'




- job: macOS
  pool:
    vmImage: 'macOS-latest'


  steps:


  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '5.0.x'
  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '6.0.x'

  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '3.1.x'

  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test
      projects: './test/NatashaFunctionUT'
      arguments: '-c Release'




- job: Windows
  pool:
    vmImage: 'windows-latest'


  steps:


  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '5.0.x'
  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '6.0.x'

  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '3.1.x'

  - task: DotNetCoreCLI@2
    displayName: restore
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command:  build
      projects: './test/NatashaFunctionUT'
      arguments: '-c Release'
      
  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test
      projects: './test/NatashaFunctionUT' 
      arguments: '-c Release --no-restore --no-build'
