name: Publish

on:
   pull_request:
     branches:
       - main
   push:
     branches:
       - main

jobs:

  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: ðŸ”¨ Setup .NET Core 3.1.X SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
        
    - name: ðŸ”¨ Setup .NET 5.0.X SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.x'


    - name: ðŸ”¨ Setup .NET 6.X SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'
        

    - name: ðŸ”¨ Setup .NET 7.X SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'


    - name: Release Dll
      run : dotnet build -c Release


    - name: Pack - Domain
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Natasha.Domain/Natasha.Domain.csproj -o .

    - name: Push to Nuget - Domain
      run: dotnet nuget push *.Domain.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

 
    - name: Pack - Compiler
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Natasha.CSharp/Natasha.CSharp/Natasha.CSharp.csproj -o .

    - name: Push to Nuget - Compiler
      run: dotnet nuget push *.CSharp.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

        


